---
title: "redundancy vs maximum matchings"
author: "Fernando Cagua"
date: "5 October 2015"
output: html_document
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(ggplot2)

opts_knit$set (root.dir=normalizePath('../'))
opts_chunk$set (fig.path = "./figures/07/")
opts_chunk$set (cache.path = "./cache/07/")
opts_chunk$set (fig.width = 11, 
                fig.height = 9,
                out.width = "858px")
```

```{r}
# load utility functions
nn <- list.files("./code/functions", full.names = TRUE) %>% lapply(source)
# load netw
net <- list.files("./data/networks/", full.names = TRUE) %>%
    lapply(readRDS)
names(net) <- list.files("./data/networks/", full.names = FALSE) %>%
    stringr::str_split("\\.") %>% lapply(`[`, 1) %>% unlist ()
```


Let's check if the redundancy matches the maximum matching results.

## Read redundancy

```{r}
node_redundancy <- read.csv(file = "./data/node_redundancy.dat")

node_re <- node_redundancy %>% 
	plyr::ddply("net", function(x){
		this_net <- net[[first(x$net)]] %>%
	# select only the largest connected component of the network
			keep_largest_component()
		nodes <- igraph::V(this_net)[x$n]$name
		x %>%
			dplyr::mutate(node = nodes)
	}) %>% dplyr::tbl_df()
```

## Read maximum matchings

```{r}
folder <- "./data/maximum_matchings_summary/" 
files <- list.files(folder)
node_mm <- plyr::adply(files, 1, function(x){
	read.csv(file.path(folder, x)) %>%
		dplyr::mutate(net = unlist(stringr::str_split(x, "_"))[1],
									type = unlist(stringr::str_split(x, "_"))[2], 
									keep = unlist(stringr::str_split(x, "_"))[3],
									batch = unlist(stringr::str_split(x, "_"))[4])
}) %>%
	dplyr::select(-X1) %>%
	dplyr::group_by(net, type, keep, node) %>%
	dplyr::summarise(freq = sum(freq))

```

## Join them 

```{r}
ranked_mm <- dplyr::full_join(node_mm, node_re) %>%
	dplyr::filter(!is.na(freq)) %>%
	dplyr::group_by(net, type, keep) %>%
	dplyr::mutate(r = rank(freq, ties.method = "random"),
								f_f = freq/max(freq))

ranked_mm %>%
	dplyr::filter(type == "weight") %>%
	ggplot() +
	geom_line(aes(x = r, y = f_f, linetype = keep)) +
	
	geom_point(aes(x = r, y = f_f, fill = robustness), shape = 21, size = 3.5) +
	facet_wrap(type ~ net, scales = "free")

ranked_mm %>%
	dplyr::filter(net == "MED3CA") %>%
	ggplot(aes(x = r, y = f_f)) +
	geom_line(aes(group = keep), linetype = 2) +
	geom_point(aes(fill = robustness), shape = 21, size = 3.5) +
	facet_wrap(~type)


```


## Role of invasive species

```{r}
	library(scales)
inv <- dplyr::data_frame(net = unique(node_redundancy$net) %>% as.character(),
												 inv = grepl("2", net) | grepl("4", net)) %>% 
	dplyr::mutate(site = rep(c("BAT", "FRA", "MED", "FAR", "MIQ", "SEL"), each =2),
								invader = rep(c("car", "op", "car", "op"),  c(2, 2, 4, 4)))
	
invasive_sp <- data.frame(node = c("p_4", "p_25"), invs.species = TRUE)
	
ranked_with_inv <- 
	ranked_mm %>% filter(keep == "A") %>% full_join(invasive_sp) %>% full_join(inv)

pdf("./presentation_figures/bp_prop_mm.pdf", width = 8, height = 5.5)
ggplot(ranked_with_inv,aes(y = f_f, x = site, fill = inv)) +
	geom_boxplot(size = 1) +
	theme_minimal() + 
	theme(legend.position = "none",
				axis.title = element_blank(), 
				axis.text = element_text(size = 16)) +
	scale_x_discrete(labels= c("site 1", "site 2", "site 3", "site 4", "site 5", "site 6")) +
	scale_y_continuous(labels = percent) +
	scale_fill_manual(values = c("#a6cee3", "#fb9a99"))
dev.off()

pdf("./presentation_figures/bp_prop_mm_inv.pdf", width = 8, height = 5.5)
ggplot(ranked_with_inv %>% filter(inv == T),aes(y = f_f, x = site, fill = inv)) +
	geom_boxplot(size = 1) +
	theme_minimal() + 
	theme(legend.position = "none",
				axis.title = element_blank(), 
				axis.text = element_text(size = 16)) +
	scale_x_discrete(labels= c("site 1", "site 2", "site 3", "site 4", "site 5", "site 6")) +
	scale_y_continuous(labels = percent) +
	scale_fill_manual(values = c("#fb9a99", "white"))
dev.off()

		
mm_prop_invasive <- ranked_with_inv %>% filter(invs.species)

pdf("./presentation_figures/bp_prop_mm_inv_species.pdf", width = 8, height = 5.5)
ggplot(ranked_with_inv %>% filter(inv == T),aes(y = f_f, x = site, fill = inv)) +
	geom_boxplot(size = 1) +
	geom_point(data = mm_prop_invasive, aes(x = site, y = f_f), shape = 21, size = 4, fill = "#e41a1c") + 
	theme_minimal() + 
	theme(legend.position = "none",
				axis.title = element_blank(), 
				axis.text = element_text(size = 16)) +
	scale_x_discrete(labels= c("site 1", "site 2", "site 3", "site 4", "site 5", "site 6")) +
	scale_y_continuous(labels = percent) +
	scale_fill_manual(values = c("#fb9a99", "white"))
dev.off()

neigh <- plyr::ldply(net, function(x){
	plyr::ddply(invasive_sp, "node", function(y){
		node <- which(V(x)$name == y$node)
		if (length(node) == 0){
			return(NULL)
		} else {
			data.frame(neighbors = neighbors(x, node)$name)
		}
	})
}) %>%
	dplyr::select(-node) %>%
	dplyr::rename_("net" = ".id", 
								 "node" = "neighbors") %>%
	dplyr::mutate(neigh = T)


neigh <- ranked_with_inv %>% filter(inv == T) %>% left_join(neigh) %>% filter(neigh) 
		
pdf("./presentation_figures/bp_prop_mm_inv_species_poster.pdf", width = 14.5, height = 5.5)
ggplot(ranked_with_inv %>% filter(inv == T),aes(y = f_f, x = site, fill = inv)) +
	geom_boxplot(size = 1, fill = "white") +
	geom_point(data = mm_prop_invasive, aes(x = site, y = f_f), shape = 22, size = 8, fill = "#e41a1c", alpha = 0.75) + 
	# geom_jitter(data = neigh, aes(x = site, y = f_f), shape = 21, size =3,  fill = "#377eb8", position = position_jitter(width = 0.25, height = 0)) + 
		ylab("species relevance\nfor management\n") +
	theme_minimal() + 
	theme(legend.position = "none",
				axis.title.x = element_blank(), 
				axis.text = element_text(size = 44),
				axis.title.y = element_text(size = 44)) +
	scale_x_discrete(labels= c("site 1", "site 2", "site 3", "site 4", "site 5", "site 6")) +
	scale_y_continuous(labels = percent) +
	scale_fill_manual(values = c("#fb9a99", "white"))
dev.off()
```

