---
title: "Dilation profile"
author: "Fernando Cagua"
date: "3 December 2015"
output: html_document
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(ggplot2)
library(ggtern)

opts_knit$set (root.dir=normalizePath('../'))
opts_chunk$set (fig.path = "./figures/09/")
opts_chunk$set (cache.path = "./cache/09/")
opts_chunk$set (fig.width = 11, 
                fig.height = 9,
                out.width = "858px")
```

```{r}
# load utility functions
nn <- list.files("./code/functions", full.names = TRUE) %>% lapply(source)
# load netw
net <- list.files("./data/networks/", full.names = TRUE) %>%
	lapply(readRDS)
names(net) <- list.files("./data/networks/", full.names = FALSE) %>%
	stringr::str_split("\\.") %>% lapply(`[`, 1) %>% unlist ()
```

Calculate the number of control

```{r}
# generate parameter space
space <- expand.grid(type = c("z-bi", "weight", "AB", "BA"), 
                                         net = 1:length(net)) %>%
    dplyr::inner_join(data.frame(type = c("z-bi", "AB", "BA", "weight", "weight"),
                                                             keep = c("all", "A", "B", "A", "B")))

# select the corresponding one for this computation

driver_nodes <- 1:nrow(space) %>%
	plyr::laply(function(i){
		p <- space[i,]
		n <- net[[p$net]] %>%
			keep_largest_component() %>%
			bipartite_digraph(type = p$type, keep = p$keep)
		igraph::E(n)$weight <- 1
		n %>%
			n_unmatched_vertex()
	})

space %<>%
    dplyr::mutate(n_driver = driver_nodes,
                                type.keep = interaction(type, keep))

net_names <- plyr::ldply(net, function(x){
    length(igraph::V(x))
}) %>%
    dplyr::mutate(net = 1:nrow(.)) %>%
    dplyr::rename(n_species = V1,
                                net_name = `.id`)

space <- dplyr::inner_join(space, net_names) %>%
    dplyr::mutate(n_no_driver = n_species - n_driver)
```

Get number of source nodes

```{r}
dilation <- 1:nrow(space) %>%
	plyr::ldply(function(i){
		p <- space[i,]
		n <- net[[p$net]] %>%
			keep_largest_component() %>%
			bipartite_digraph(type = p$type, keep = p$keep)
		igraph::E(n)$weight <- 1
		out_degree <- igraph::degree(n, mode = "out")
		in_degree <- igraph::degree(n, mode = "in")
		n_sources <- sum(out_degree > 0 & in_degree == 0)
		n_sinks <- sum(out_degree == 0 & in_degree > 0)
		n_ext_dil <- max(0,n_sinks - n_sources)
		data.frame(type = p$type, net = p$net, keep = p$keep, 
							 n_sources = n_sources, n_sinks = n_sinks, 
							 n_ext_dil = n_ext_dil)
	})

dilation <- inner_join(space, dilation) %>%
	dplyr::mutate(eta_s = n_sources / n_driver, 
								eta_e = n_ext_dil / n_driver, 
								eta_i = 1 - eta_s - eta_e)
```

Let's have a look

```{r}
library(ggtern)

ggplot(dilation, aes(x = eta_s, z = eta_e, y = eta_i)) +
	geom_point(aes(fill = type.keep), shape = 21, size = 5, alpha = 0.7) +
	coord_tern() 
```

Save the data

```{r}
write.csv(dilation, file = "./data/dilation_profiles.dat", row.names = F)
```

