---
title: "Ecological network control" <!-- DBS really doesn't like the new title... -->
classoption: a4paper
csl: journal-of-ecology.csl
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    number_sections: false
toc: false
header-includes:
- \usepackage{setspace}
- \usepackage{float}
- \usepackage{booktabs}
- \usepackage{caption}
- \usepackage{lineno}
documentclass: artikel1
bibliography: references.bib
---

\doublespacing
\linenumbers

**E. Fernando Cagua^1^, Kate L. Wootton^1,2^, Daniel B. Stouffer^1^**

^1^ Centre for Integrative Ecology, School of Biological Sciences, University of Canterbury, Private Bag 4800, Christchurch 8041, New Zealand

^2^ Current address: Department of Ecology, Swedish University of Agricultural Sciences, Box 7044, SE-750 07 Uppsala, Sweden

**Author for correspondence:** Daniel Stouffer (daniel.stouffer@canterbury.ac.nz) - +64 3 364 2729 - Centre for Integrative Ecology, School of Biological Sciences, University of Canterbury, Private Bag 4800, Christchurch 8140, New Zealand

\newpage

# Introduction

<!-- I think there is a sentence missing before or after the following sentence. If before, it's about the desire to understand roles; if after, it's about how species have many types of roles, and one of particular interest is the role in "functioning". That said, I'm not certain that 'functioning' is the best catch-all for what we explore here.... -->
Within community ecology, a complex-systems approach has led to the development of analytical and simulation tools with which to understand the role of species embedded in a network of interactions [@Bascompte2009; @Stouffer2012]. 
A particularly relevant dimension of any species' role is its ability to alter the abundance of other species in the community, since this impacts ecosystem functioning, XXX, and YYY. 
This ability is often referred as species importance or "keystoneness". 
A significant proportion of the network tools used to estimate species roles in this context relies on the assumption that there is a link between a species centrality---DEFINE CENTRALITY VERBALLY---and its importance. 
<!-- Simplify the beginning of the following sentence as it's more complex than it need be, no pun intended. -->
At first glance, this assumption makes sense because at the core of representing ecological communities as complex systems sits the idea that the abundance of any given species depends on its abundance, the abundance of the species it interacts with, the abundance of the species they interact with, and so on. 
More central species, by definition, are better connected and hence should be more likely to affect the abundance of other species in the network.

Though conceptually intuitive, the relationship between centrality and role is largely phenomenological, and recent studies have shown that definitions of role based on centrality might not adequately estimate the relative influence of a species on its community. <!-- Seems a bit weak. Would an example help? -->
This has important consequences not only for the theoretical understanding of ecological communities but also for potential conservation applications. <!-- Again, concrete examples help ground statements like this. -->
As a results, community ecology could benefit considerably from an alternative, more mechanistically-grounded, approach to relate species to ecosystem functioning. <!-- are we sure functioning? -->
Ideally, such an approach should account for the structure of the interactions in the community, just like centrality based methods, and without requiring a priori assumptions about how particular network metrics relate to changes in species abundance. 
This is because species abundances are also influenced by the dynamic relationships between nodes, and the mechanisms of self-regulation. 
However, community and population dynamics can be modeled in innumerable ways, and empirical support for one versus another is often still ambiguous. Therefore, the ideal alternative approach should also acknowledge ecosystem dynamics without being overly dependent on the particular choices of how they are characterised.

Among the various possibilities, *control theory* appears to be a strong candidate to be used to define a species role for ecosystem functioning [@Isbell2013]. 
*Control theory* is a widely studied branch of engineering used to determine and supervise the behaviour of dynamical systems [@Motter2015]. 
It is inherently designed to deal with system feedbacks and its application has recently been expanded to complex networks [@Liu2016]. 
In correspondence with ecological questions, advances in this field have established a clear link between the structure of the network and the way nodes affect each other. 
Unlike ecological approaches, however, this link is not based on a priori assumptions but instead on well-established advances in both dynamical and complex-systems theory. <!-- Are we shooting ourselves in the foot since this isn't entirely true? That is, see comments from ELE about linearity and otherwise.... -->


Despite the apparent overlap, the concepts and approaches of control theory are not yet commonly applied in an ecological context. 
Possibly, this is in part because, in contrast with ecology, research on the control of complex networks is generally more concerned with the state of the system as a whole than the nodes that compose the network. <!-- Shift the "in contrast to ecology" into it's own sentence here? -->
At its fundamental level, control theory first determines whether a system is controllable or not; that is, it asks if a system can be driven to a desired state within a finite amount of time. 
Nevertheless, it has been recently shown that asking for the controllability of a complex system is equivalent to asking whether there exists a non-trivial set of nodes with which is possible to control the state of the whole network. <!-- This sentence needs simplification. -->
Notably, this set of nodes is not always unique for a given network. This implies that an examination of the distinct sets of nodes provides a means to connect nodes with its *general* ability to modify the system to which they belong. 
Our first contribution is to expand existing methods control theory to effectively link the *controllability* of a network with the role of particular nodes. <!-- See comment below at very end of intro; I really don't think this sentence fits here.... -->

After overcoming this first hurdle, we can then apply the methods to an ecological problem and show how it can be used to gain insight into the role of species in an ecological network. 
<!-- I think the offending sentence fits here better with a corresponding rewording if the first sentence of this paragraph which will below a lot from the sentence just below this comment of mine... -->
Specifically, we outline the approach using a set of ten pairs of uninvaded and invaded plant-pollinator communities. 
We use invaded communities because there is strong empirical evidence showing that invasive species play an important role shaping the abundances of other species, and particularly in these 10 (???) networks [@Lopezaraiza-Mikel2007; @Bartomeus2008]. 
This choice thus offers us an opportunity to explicitly contrast theoretical observations with empirical evidence. <!-- I love this point. You're peering into my soul! -->
First, grounded in the difficulties usually involved with invasive-species eradication and ecosystem restoration [@Woodford2016], we ask whether invaded networks require a greater proportion of species to be managed to achieve the same level of control. <!-- I'd remove the grounded in.... stuff, but that's just me. -->
Second, we ask—from a control-theoretic perspective—whether there are key differences between species in the role they play at driving the population of other members of the community and identify the ecological factors related to these differences. 
Finally, we compare the proposed approach to current methods based on species centrality and show how these methods are indeed valuable but only paint a limited picture in regards to the "keystoneness" of a species.

<!-- I don't really like how the "what we do" parts of the intro are split across two paragraphs. It feels clunky... -->

# Methods



```{r example_network, include = F}
loadd(example_net)
	
base_net <- example_net
	bi_net <- example_net %>%
		keep_largest_component() %>%
		bipartite_digraph(type = "z-bi", weight.type = "asymetry") 
	as_net <- example_net %>%
		keep_largest_component() %>%
		bipartite_digraph(type = "weight", weight.type = "asymmetry")
	
	fam <- "Helvetica"
	
	# layout is based on the bidirectional network
	set.seed(1)
	bi_net_uw <- bi_net
	E(bi_net_uw)$weight <- 1
	lay <- bi_net_uw %>%
		layout_nicely()
	v_c <- "white"
	l_c <- "black"
	l_s <- 0.9
	ma <- c(0,0,0,0)
	label_pos_x <- -1
	label_pos_y <- 1
```

# References
