---
title: "Response to reviewer comments ELE-00738-2016"
date: "14 December 2016"
output: pdf_document
classoption: a4paper
bibliography: references.bib
header-includes:
- \usepackage{setspace}
---

\onehalfspacing

Dear Prof. Jonathan Chase, 

We are grateful for the opportunity to resubmit a revised manuscript for your consideration. 
We have endeavored to incorporate all reviewers' feedback into the manuscript and we feel the attached draft constitutes an important improvement from the previous version. 
We were impressed by the quality of the reviews; they all were thoughtful, clear, and constructive. 
It is evident that all three anonymous reviewers have given a fair and careful consideration to our manuscript. 
We would like to thank them for the truly valuable feedback. 

The reviewers identified major limitations in our manuscript. 
Specifically with regards to the terminology, the underlying  structural control, and the lack of detail in the presentation of the empirical networks. 
In the current version, we have thoroughly addressed all these concerns and improved both the robustness of the analyisis and the clarity of the concepts. 
Detailed responses to each comment, one by one, are provided in the corresponding section. 

Fernando Cagua

******************************************

## Response to the handling editor

We are thankful for the encouraging assessment that our work "has excellent potential" and "could have major impacts on applied ecology". 
We have fully addressed the flaws pointed by all the reviewers and, in the process, took advantage of this opportunity to incorporate some further changes that in our opinion improved the quality and thoroughness of our assessment.

The most substantial change is related to the result that ecological invasions reduce the manageability of the studied pollination networks. 
After revising the manuscript, we found that the effect of invasion is actually the opposite of what we initially reported. 
This result arises from a regression in which the response variable was the proportion of driver nodes. 
Our previous conclusion arose from a trivial mistake on the implementation of this regression for which we are extremely apologetic. 
The regression indicates that the invasion status is *inversely* related to $n_D$ (the density of driver nodes) and **not** to our previous definition of manageability $m = 1- n_D$. 
We highlight that although the corrected result now contradicts our hypothesis, our postulate has remained unchanged and the applicability of our approach is maintained. 
It is possible that the root of the mistake was, as you and the reviewers helpfully pointed out, that our definition of manageability and its relation to previous conceptions of controllability were confusing. 
Now, we refrain from giving a mathematical definition to manageability and instead focus on $n_D$, an unambiguous metric clearly defined in the structural controllability literature. 

We extend this approach to our investigation on the relative importance of species. 
In the previous manuscript, we referred to species that were classified as superior nodes in all possible control strategies as *driver species*. 
Because of the similarities with the term *driver node*, which has been used in previous literature and we also use in our manuscript, it was extremely easy to misinterpret the terms and follow our rationale. 
Now, we have removed the term driver species and instead focus on two straightforward metrics: $f_D$ and $f_S$, which more clearly correspond to the frequency to which a species is classified as a driver or superior node, respectively. 

Finally, we have made important modifications to the section in which we explain the theoretical underpinnings of structural controllability. 
We hope it is easier to follow both for experts and newcomers. 
We also have included a significant amount of detail and extra examples in the supplementary material to simplify the lives of those interested in applying the proposed approach or replicating our results. 

## Referee 1

In ms ELE-00738-2016, the authors seek to apply ideas from control theory (specifically, structural controllability) to bipartite ecological networks. The main idea of structural control theory, at least in the recent applied literature, is that some nodes are recipients of external, time-varying control signals that proceed to propagate through a network in such a way as to drive the state of every node in the network to a desired configuration in finite time. There tend to be many ways to do this, and nodes can further be characterized by the frequency with which they exist on key paths leading through the network.

These ideas have been used as additional measures to describe the topological characteristics of networks as they relate to their control. The novelty of the present ms is in extending these ideas in a rigorous way to mutualistic ecological networks, which to my knowledge has not yet been done (some existing work includes ecological networks, but usually in a somewhat cursory way).

This is a powerful premise and, at least in principle, a ms with such a focus could be a good candidate for publication in Ecology Letters. However, I have numerous concerns with the manuscript. The methodological assumptions of structural control are never discussed (i.e., what is the assumed form of the dynamic relationship between interacting nodes?), the extent to which this is or is not realistic in an ecological context is not discussed (it seems to me that there are important caveats), other details of the theory are left unexplained, a key term is used in a different context than in the control literature (which will needlessly confuse readers), and some of the statistical analysis seems questionable.

I expound on this overview in some detail below. I regret that I cannot be more enthusiastic about the manuscript in its current form and I wish the authors luck as they revise their manuscript.

- The authors begin by stating, "Complex systems are characterised by non-linear relationships...", however, there is an entire branch of work devoted to network control that explicitly assumes linearity on the level of specific interaction (see e.g. doi 10.1126/science.1242063 and doi 10.1038/nature10011, both of which the authors cite). It seems to me that the authors could simply remove this bit of text and restructure the sentence to make the same point -- that complex systems are often viewed as being "greater than the sum of its parts."

    *Accepted; changed.*

- The paragraph on lines 50-62 cites papers published no earlier than 2011. However, to support the following argument "Despite these advances, the link between the structure of complex networks and our ability to manage and conserve them is still ambiguous", the authors cite a paper that predates all of them (Tylianakis et al. 2010). The paper in question highlights practical challenges to conservation; many if not all of them remain today (which I suspect is the authors' argument). I suggest the authors revise the text to make the contribution of this reference clear.

    *We revised the text to better reflect the contribution of @Tylianakis2010 at the same time we added a reference to a more recent paper by @Kaiser-Bunbury2015 who explicitly deals with oportunities, limitations and implications of applying network metrics in conservation science.*

- Lines 95-97: "The number of nodes necessary to fully control a complex network can be calculated by counting the number of unmatched nodes in the network's maximum matching (Liu et al. 97 2011)." This statement must be contextualized by the assumed nature of the dynamical relationships in this framework. It therefore seems to me that this statement should be preceded by a discussion of those details (indeed, the authors argue that this is necessary in the Introduction, on lines 48-49). Furthermore, the authors need to discuss the appropriateness of this framework to ecological systems. The input control signals that drive even relatively simple networks to specified states can be very sensitive to initial conditions and complicated (indeed, they usually aren't calculated at all). How can a control scheme be implemented even in principle if nodes represent species populations and a control signal calls for a fractional change in a node state variable over the course of minutes? 

    *Thanks to this comment and those from other reviewers have helped us identify some shortcomming on the way we were introducing the control framework in the paper. We have largely rewritten the 'Theoretical framework' section and we start by offering a brief overview of control theory which emphasize on a dynamical perspective to complex networks (Line XXX). We then follow with a paragraph devoted to how structural controlability is unable to provide information about the particulars of the control signal and the feasibility of its application (Line XXX). Without disregard the usefulness of the proposed approach, we also mention in this paragraph, and later on the discussion (Line XXX), how recently developed numerical methods [@Cornelius2013] might offer exiting results in this regard.*
    
- Furthermore, how do the authors interpret the methods by which cycles are controlled in linear control theory (see e.g. doi 10.1126/science.1242063 and its supplementary material) in the context of ecological management? How frequent are cycles in the authors' ecological networks? I should emphasize that I am a fan of control theory and I think it is interesting to apply it as the authors do in this ms. However, the caveats that come along with the points I outline above need to be made clear for the reader. The authors might be interested in doi 10.1063/1.4931570 for a discussion of some relevant ideas.

    *Thanks for pointing this out. In fact we thoroughly implememnted the approach of [@Ruths2014] at initial stages of the project. However we found that the profile of the network depends to an extreme degree on the chosen link directionality and very little on the particulars of a given network. Because of that reason we decided to exclude this approach altogether from the final draft. Nevertheless, due to this comment and one of Referee 2 we included this treatment in the Supplementary Materials Section XX and reference it briefly in the manuscript (Line XXX). In SM SectionXX we explain that because we focus on bipartite networks, cycles only appear, and in fact dominate, when we consider the case of bidirectional links. We are particularly grateful for the reference to @Motter2015. We were unaware of this paper and has been extremely useful to contextualise our work in the broader control theory.* 
    
- Lines 101-103: "(ii) the sum of the weights of the matched links—known as matching weight—is the largest possible among all possible matchings of that size (West 2001)." The authors go on to cite Liu et al. 2011, but that report (and many others cited in the present ms) considers "structural controllability", which assumes binary edge weights (i.e., they exist or they do not). Is condition (ii) appropriate here? If so, why? The authors get at this later in the ms (lines 145-152, where it looks as if edges are indeed binarized), but for readers familiar with the structural control literature, there is room for confusion as they come to this point in the ms. This may be mitigated as the authors address my comment 3, but it seems appropriate for me to raise this point explicitly as well.

    *Indeed most of the literature treats the problem of controlability on unweighted networks. It has been shown, however, at least in pollination networks like the ones used in our paper, that the interaction weights carry important information about the patterns and processes in the community. In the paper we use the visitation weights directly or indirectly in two different aspects. First, we use them to determine the direction of control (via the dependence asymetry). Second, which directly adresses the reviewer's comment, we use it to give priority to matchings that have the largest weight, which potentially also have the largest impact on the network state for a given management intervention. Because the weights determine to some extent the dynamical relationships between species, our approach attempt to incorporate more realism to the structural controllability approach. We acknoweledge our presentation was confusing, especially for readers familiar wit the control literature, and therefore have added a whole paragraph in the method describing our rationale (Lines XXX)*

- When defining n_d on line 119, it is more accurate to say that it is the "minimum number" of species needed to gain full control.

    *We have rewritten that section and the equivalent sentence now reads "It has been shown that a particular network that can be expressed as a state space system of the form $\dot{x} = Ax + Bu(t)$ is controllable if there exists a minimum number of nodes in the network (N~D~ > 0) to which is possible to aply an external control signal that propagates trough the network to in turn drive the state of every other node in the network to a particular configuration [@Kalman1963; @Liu2011]."*

- Lines 132-133: "...we therefore call driver species those that are identified as being a superior node in all possible matchings..."
I have several comments here. First, shouldn't this be "all possible maximum matchings"?

    *We are sorry for the impresicion. It should have been "all possible maximum cardinality matchings". In any case, because of the suggestion about the driver species concept we have decided to remove this sentence. We also reworded the text in Lines XXX to clarify why our approach to identify species importance is not exclsively centered on maximum matchings.*

- Second, a node with no outgoing edges will clearly never be a superior node and will therefore not be a driver node. I assume that this never happens in the mutualistic networks under consideration, but this probably bears mentioning so as to help develop the reader's intuition for this assessment. In any event it would be useful for the reader to see a simple network (or several) to provide clear examples of driver nodes and non-driver nodes. For instance, how can a node with an outgoing edge not be a driver node?

    *Thanks to this suggestion and those of other reviewers, we have made important changes to Figure 1. On it we include a better ilustration of our methodology for a simple network while paying special effort to bring clarity to the different node categories as superior, matched and unmatched nodes. TO DO*

- Finally, the term "driver species" (or more generically, "driver node") has a specific meaning in the control literature (doi 10.1038/nature10011): what the authors here denote with n_d on line 118. To avoid confusion with those familiar with the control theory literature (and those readers who are inspired by this ms to delve into it), I suggest a change of terminology. Perhaps "key species"?

    *Overall our choice of terminology was poor. We have eliminated the term "driver species" from the manuscript and now just mention, in the referee's words, how the frequency with which species exist on key paths trough the network provides indication of their relative importance.*

- The approach described in lines 145-152 would be clearer if the authors included a figure demonstrating each step for a simple network.

    *Thanks for pointing this out. As suggested, we have included a figure that help explains our method to compute all possible maximum cardinality matchings. However because the methodology itself is not one of our main contributions and because of space limitations we have included that figure in the Supplementary Material. TO DO.* 

- Lines 173-176: "To do so, we calculated the maximum matching of the corresponding pollination network, and estimated the minimum proportion of species that need directed interventions to fully control the species abundances in the community." Why is this an estimate? The number of species that need to be directly controlled can be determined unambiguously.

    *We apologise for the poor choice of words. As the referee points out it is not an estimation but an exact calculation. The sentence now reads "To do so, we calculated the maximum matching of the corresponding pollination network, and determined the minimum proportion of species that need directed interventions to fully control the species abundances in the community".*

- It seems to me that the number of interactions would also be an interesting factor to consider in the statistical analysis (discussed beginning on line 213).

    *Thanks for the observation. We have now included the number of interactions in the network as an extra explanatory variable. TO DO*

- Lines 225-228: "Previous research indicates a direct link between a network's degree distribution and the number of nodes necessary to fully control it (Liu et al. 2011), but the strength and applicability of this relationship has not been tested for in weighted ecological networks." The authors go on to discuss null models that vary edge weights. However (as mentioned in comment 4), it seems to me that the edge weight is ultimately not a factor when determining the manageability of the network, at least once it has been mapped to unidirectional and unweighted edges. The methodology and rationale here needs to be clarified. For instance, is the effect of changing edge weight restricted to affecting interaction asymmetry and thereby the unidirectional projection of the interactions? If so, how does this differ from the null model that does this explicitly (described on lines 239-246)? Does edge weight play any other role in this analysis? (Its role is clear in the section beginning on line 247.)

    *In retrospect we realise that we did not have a clear rationale to include an randomisation of the link weights. As the referee points out, a change on the weights would only be reflected on a potential change on the interaction asymmetry. We identifyed two problems with this approach: first the changes aren't easily tractable, and second there is not a standard way to randomise weight in quantiative networks and the particular choice of the algorithm might influence the results. We therefore decided to remove the null model that maintained the degree of species and randomised the weight of the links as the effect of the asymetry is explicitly tackled by the second approach in which we maintain the structure but randomise the asymmetry.*

- It seems useful to mention the typical size of the networks at the beginning of the results, if not earlier. In addition, the fact that the mean value of m is 0.37 means that roughly two thirds of the species in these communities need to be directly controlled, at least according to this modeling framework. It seems to me that this merits explicit comment in the Discussion.

Indeed, in the Discussion the authors say for example, "Because of their effects on other species in the community, driver species might be natural candidates for management interventions." This may be true, but it seems to me that the role of the directly-controlled species (that populate n_d), which serve as the gateway for the control signals to the rest of the network, merits discussion here as well. How are the two related? Do the authors envision a scenario where a control signal is actually being sent in to the network? Or do they rather envision a scenario where no controls are being used (which is counter to the central idea of structural controllability), and are they instead identifying these drivers nodes simply to provide a proxy measure of the effect of node state perturbations on the rest of the network? The latter seems more plausible than the former, but in any case more detail is needed.

- Figure 3 should show the distributions of m as well as the adjusted value of m. I suggest also providing more detail about how the adjusted value is calculated (in the current version there is one technical sentence that non-experts will not be able to follow).

- In Appendix S2 (referenced in the ms on lines 205-208), the authors state that the relative number of driver species, while different for the approaches there discussed, are not significantly different from one another. However, the statistical test used is a Spearman correlation coefficient, which does not measure the difference in e.g. population means but rather the extent to which their relationship is monotonic.

Minor comments
Line  236: there is a missing period.


## Referee 2

This manuscript proposes to apply the methods published in previous papers (e.g. Liu et al, Nature 2011) on the controllability of complex systems to invaded pollination networks. Note that controllability is rebranded “manageability” (unless it has a different meaning in this paper?). The manuscript also proposes to identify the nodes to manage or driver species. This is a fascinating area of research.
Performing a controllability study on ten pairs of uninvaded and invaded plant-pollinator networks, the main finding is that invaded networks require a higher number of nodes to control than their non-invaded counterpart and invasive plants were driver species in all studied communities.
The study is scientifically sound. However the manuscript is dense and difficult to read. In particular the section Theoretical framework and its subsection are confusing and should be merged with the Methods section. The discussion should be strengthen.
In its current form, it is unlikely that readers will be able to understand or replicate the research presented – which is a shame considering the authors went through a lot of trouble to apply a control theory study in an ecological context. An overall simplification of the language/sentences and jargon used will increase the readability of this manuscript. Ruths (2014, Science) and Liu (2011, Nature) are doing a better job at explaining maximum matching, driver nodes and the overall challenge of controllability.

- Consider being more specific in your abstract.

- L74 “we expand previous theory of the control of complex systems to an ecological context”. Do you mean apply? Please clarify your contribution without ambiguity.

    *The sentence now reads "To bridge this gap, we develop methods to apply previous theory on the control of complex systems into an ecological context and implement them using empirical data, while taking into account the quantitative differences that exist among species interactions."*

- Section Manageability (L94). Please first define manageability before maximum matching. Also, the maximum matching paragraph is difficult to understand. Reword.

    *We have pretty much rewritten the "Theoretical framework" section following the reviewers advise. We start with a brief introduction to structural controllability (Lines XXX), follow with a definition of manageability (Lines XXX) and finalise with details and computational considerations for its calculation.*

- Section Relative importance (L121). It seems that the abstract refers to this section as being a novel way to identify communities’ driver species. However it is very unclear that this is a novel contribution. Please clarify in the text and provide details in supplementary information. It is also unclear from the Methods section.

     *Thanks for the observation. We have reworded large segments of this section. Specifically now explain how the approach builds on existing structural controllability theory by incorporating the weight of the interactions. Moreover, now we included more details about the rationale behind our approach. By being more specific we hope the reader to be able to identify the theretic and computational novelties of our approach with respect to existing "ranking" methods. We also strive to further clarify the novelty in the discussion section (Lines XXX). TO DO*

- Discussion. McDonaldMadden et al (2016) actually show that network metrics are not useful to prioritise the management of foodweb, i.e. to determine which species should be managed first (if required). Please edit current text and analyse differences with your work.

- Discussion. Please provide some insight into how your method/analysis/results would differ for non- pollinator invaded networks.

- Discussion. Please discuss the caveats of your approach. I suggest moving some of the statistical analyses in sup info if word limit is an issue.

- The maximum matching algorithm is computationally expensive as noted by the authors. In Ruths & Ruths (2014) the authors come with an interesting alternative to calculate the minimum number of independent controls (driver species) using only the number of source nodes, external dilation points and internal dilation points; and a heuristic using source and sink nodes. What is the profile of the pollinator networks studied? Would the Ruths & Ruths approach be an easier way of reaching the same conclusions? Would it bring complementary information?

- A few typos in main text and sup info.

- Is there a compelling reason to change controllability to “manageability”? Walters did the same thing with “adaptive management” in lieu of “adaptive control”. 30 years later, no one remembers where “adaptive management” originally came from and it has become a keyword in ecology. As a result, ecologists have been cut from the theoretical advances in control theory and most often have no clue that these are the same thing.

## Referee 3

In this work Cagua et al apply tools rooted in control theory to ecological networks and discuss how this approach could be used for management of natural systems, with emphasis on the effects of invasive species. This is an exciting work. It presents to ecologists a novel way of studying the relationship between topology and dynamics that is less dependent (when compared to other methods) on particular choices about how dynamics are modeled. The authors illustrate the potential of this approach by exploring how invasive species change system dynamics and manageability. My only concern about this manuscript is that the authors need to be more careful and more explicit about some limitations of this approach and the generality of their results, specially considering the implications of their results for management.

 - Only one type of interaction is being considered here when species are involved in multiple types of interactions. An assumption that is not explicit in the text is that all the factors controlling population densities are the interactions between plants and pollinators. The boundaries of a network, including the types of interactions that are considered or not, are often arbitrarily defined. However, this approach is highly dependent on the topology of the network and thus on how we define the network. I know this limitation applies to any study on system dynamics, but it becomes more serious when we argue that management decisions can be based on a single technique. I have two suggestions. First, the authors should discuss in detail these assumptions and their limitations. 

    *PARTIAL ANSWER: We have included some comments about the general limitations of the structural controlability approach in the "Theoretical Framework" section (Lines XXX). Furthermore*

Second, It would be helpful if the authors could test the robustness of their results to sampling. The results show that invasive species change manageability. This suggests that manageability may be sensitive to sampling. A sensitivity analysis where species are added and removed from the network under different wiring schemes would help us understand the behavior of the manageability index when networks are undersampled and would allow a more informed discussion on how the choices we make when delimiting the network affect estimates of controllability. Weak links should not have a strong effect on controllability and considering the networks were built using visitation frequency, most of the strong interactions were likely sampled. Still, it would be great to show that the method is robust and this would make it easier to justify that even in the absence of complete sampling this technique is in fact useful for management.


See more specific comments below.

- Ln 25. I don't think that the statement that you "expand theory on the controllability of complex systems" is accurate. It is not clear to me how these results contribute to expand the general theory

    *Thank you. We have apologise for the imprecision. The sentence now reads "To bridge this gap, we develop methods to apply previous theory on the control of complex systems into an ecological context and implement them using empirical data, while taking into account the quantitative differences that exist among species interactions", which better reflects our contribution.*

- Ln 52, typo: presents

    *Thanks. It's been changed.*

- Ln 59. Please rewrite this sentence. it's not clear what "they" refers to here.

    *Thanks. The subject was intended to be "control theory". We have rephrased the sentence to improve clarity and it now reads "Therefore, control theory can potentially provide an indication of which species are most relevant from a structural and dynamic perspective, a particularly important feature given that these species should underpin informed attempts to both alter or maintain the ecosystem state".* 

- Ln 78. It is not clear why this is the direction of the hypothesis. Did you already have any indication that networks with invasive species should have lower manageability? Is there any theoretical explanation for this expectation?

    *We based the direction of the hypothesis in the general feeling of failure of several restoration ecology programmes. However, in retrospect, we realise that the academic evidence to substantiate the hypotheis was insufficient. We have reframed the sentence to indicate that invaded communities might have different levels of manageability but without an a priori expectation on the direction of this difference. REVISE, CHECK WITH WARWICK*

- Ln 95-98. It is very hard to keep track of all those definitions - matching, matched nodes, matched links, matching size, matching weight, maximum matching. I found myself going back and forth several times between the framework, methods and results sections. A glossary would help a lot.

    *Thanks. We have rewritten a large section of the methods and tried to be more clear when defining new terms by providing some examples and using a more logical sequence to go from one concept to the next (Lines XXX). We have also included a short glossary with the most important definitions. TO DO*

- Ln 99. Indicate how the matching is represented in the figure. e.g.,  "(dark grey links in Figure 1a)". Figure 1.Indicate the driver nodes in these networks

    *We have redesigned Figure 1 and now we indicate more clearly how the matching works and specify which are the superior, matched, and unmatched nodes. Also because we also illustrate the methods to obtain the relative importance, it is easier to highlight which are the key species in a simple network.*

- Ln 128. Be clear about the meaning of resources here. I understand you mean financial resources not  resources in the ecological sense.

    *Indeed. We apologise for the imprecision. We indeed mean financial resources. We have modified the sentence to improve clarity and it now reads "Ecologically, these distinctions are relevant because management and conservation resources are limited and therefore ecological interventions should ideally be focused on species that might provide the largest impact."*

- Ln 236. Typo: missing period

    *Thanks. We corrected it.*

- Ln 293: Typo: reference

    *Thanks. We corrected it.*

Ln 303-305. Please explain here which is the response variable that the ratio of plant to pollinator can explain.

Ln 326. "The strength of the dependency" has been defined as species strength by Bascompte et al. 2006. Why are you using a different term here?  When you say strength of the dependency it is not clear if you mean strength of dependencies of a given species on other species or the strength of the dependencies of all species on the species of interest. Moreover sometimes you use dependence and others dependency.

Ln 336. Liu et al. 2011 found that driver nodes were often peripheral nodes in the network instead of network hubs. Here you find the opposite. How can you explain these differences?

Ln 343 and Figure 4. Here and in the figure legend you say the level of manageability of empirical networks is lower, but in the figure you show an index that goes in the opposite direction, i.e.,  we see lower values for the randomization. It would be better to present these results in a more intuitive way.

Ln 362. Again the idea that supergeneralists tend to be driver species contrasts with Liu et al. results. This should be explored in more detail in the discussion.

Ln 372. It is important to say that vulnerability is related change, but that it is had to predict in which direction the system will change

Figure 5 legend. Please include here the definition of dependency strength so the reader does not need to go back and forth.



## References
