---
title: "Response to comments ELE-00205-2017"
output: pdf_document
csl: ecology-letters.csl
classoption: a4paper
bibliography: references.bib
header-includes:
- \usepackage{setspace}
---

\doublespacing

Dear Dr Jonathan Chase, 

We are thankful for the opportunity to resubmit our manuscript for consideration. 
In our response to the handling editor section (below), we have endeavoured to explain how our approach still provides ecological insight despite the assumption of linearity. 
To aid in the review process, we have included the response to the reviewers' and editor's comments of the previous submission (ELE-00738-2016) in this document as well and have updated the references to line numbers when appropriate. 

Before we dive into the detailed responses, we would like to draw your attention to the fact that the major concern identified by the new handling editor—the assumption of linearity—was not actually overlooked in the previous round of review. 
In the initial version of the manuscript, we mainly focused on details of the method and the study system and only mentioned in passing that our approach is based on a linearization of the network of interactions. 
Reviewers 3 and 1 in particular did not find this to be a fundamental problem; nevertheless they encouraged us to be explicit about this assumption and thoroughly discuss the implications of this simplification. 
In hindsight, perhaps these changes focused too intensely on the potential limitations of our approach and did a poorer job of justifying its advantages.

We hope this response and the modifications made to the main text are convincing enough for the manuscript to be reconsidered for publication at Ecology Letters. 

## Response to the handling editor

We agree with the handling editor that the most notable limitation of our approach is that it is based on a linear approximation of the dynamics of the system. 
Naturally, it is important to take this limitation into account when applying the framework. 
We disagree, however, with the conclusion that this limitation renders the approach ecologically irrelevant. 

We approach the editor's comments in two stages. 
First, we argue that linear models can be useful to describe the dynamics of ecological communities, and pollination communities in particular. 
Additionally, we believe that the editor's observations potentially arises from a misunderstanding of the scope and goals of our study.
Therefore, we then provide some further clarification in this regard and to structural controllability. 
Finally, we provide a detailed account of the editions we have done to the manuscript in order to prevent this kind of misunderstandings. 

While ecological systems are inherently non-linear, variations of Lokta-Volterra and other linear response models have been widely and recently used in ecology to describe both multitrophic ecological communities [@Heckmann2012; @Heath2014] and mutualistic pollination networks [@Lever2014; @Rohr2014; @Valdovinos2016]. 
Importantly several studies have found that, despite the lack of realism, parametrizations with linear responses can provide a good starting point to investigate community stability (ref), population size [@Mackinson2003], and relative species importance [@Zhao2016]. 
Similarly, we view the structural controllability as a *starting point* to investigate the way ecological communities could be steered from an equilibrium point to another in an informed fashion.

Furthermore, the editor points out that a structural controllability approach would not be useful in ecological systems because it will be "only valid in an infinitesimal border" around an initial equilibrium point. 
This comment would be completely appropriate if the local linear approximation at the equilibrium point were used to *design* the—inherently non-local—control trajectory that drives the system to an alternative state. 
Our manuscript, however, has a different aim. 
We use the structure of interaction network and determine the set of possible "control interventions" to gain network and species-level ecological that could be used in management settings.

In our manuscript, a control intervention is a set of species with which full control of the community could be gained. 
The control interventions we study are optimal from a structural point of view.
However, in practice, some of these interventions would be more appropriate than others depending on several factors like the starting and end state of the community, the feasibility of modifying the abundance of some species, the available resources, and naturally the particular dynamics of the system. 
As the behaviour of the community is governed by both structure and dynamics, by extension, our approach is ill suited to design a specific control trajectory. 
Again, we emphasise that this was not our objective and that the development of numerical approaches like the one proposed by @Cornelius2013 might be more promising in this regard. 

Nevertheless, we see the fact that we focus on structure as and advantage rather than a disadvantage. 
As one of the previous reviewers highlighted, our manuscript "...presents to ecologists a novel way of studying the relationship between topology and dynamics that is less dependent (when compared to other methods) on particular choices about how dynamics are modelled". 
It can, therefore, be used to gain insight from different ecological systems and is readily applicable to currently available data. 
Furthermore, by focusing on the network structure, the conclusions obtained will be locally valid, not only close to equilibrium points but anywhere as long as the species interactions remain. 

Specifically, we made the following modifications to the manuscript. 
In the intro we ...
As before, in the methods section, we start by stating the assumption of linearity (Lines XXX). 
However, we now also explicitly explain how this assumption does not invalidate the gained insight (Lines XXX). 
Finally, in the discussion we ...

****

# Response to comments ELE-00738-2016

## To the handling editor

We are thankful for the encouraging assessment that our work "has excellent potential" and "could have major impacts on applied ecology". 
We have fully addressed the flaws pointed by all the reviewers and, in the process, took advantage of this opportunity to incorporate some further changes that in our opinion improved the quality and thoroughness of our assessment.

The most substantial change is related to the earlier result that ecological invasions reduce the manageability of the studied pollination networks. 
After revising the manuscript, we found that the effect of invasion is actually the opposite of what we initially reported. 
This result arises from a regression in which the response variable was the proportion of driver nodes. 
Our previous conclusion arose from a mistake in our implementation of this regression for which we are extremely apologetic. 
In actual fact, the regression indicates that the invasion status is *inversely* related to $n_D$ (the density of driver nodes) as opposed to our previous definition of manageability $m = 1 - n_D$. 
After catching this error, the editor and reviewers will now note that revised result now contradicts our hypothesis and has also led to our having to amend the title of the paper. Nevertheless, we hope that you will agree that both our overall objective and the applicability of our approach is maintained. 

Upon reflection, we also suspect that the root of the mistake was, as you and the reviewers helped point out, that our definition of manageability and its relation to the existing concept of controllability were overly confusing. 
In the revised paper, we refrain from giving a mathematical definition of manageability and instead focus on $n_D$, an unambiguous metric clearly defined in the structural controllability literature. 
We also extend these attempts to use the existing nomenclature rather than introduce new terms in our investigation of the relative importance of species. 
In the previous manuscript, we referred to species that were classified as superior nodes in all possible control strategies as *driver species*. 
Because of the strong similarities with the term *driver node*, which has been used in previous literature and that we also use in our manuscript, it was extremely easy to misinterpret the terms and completely follow our rationale. 
We have now removed the term driver species and instead focus on two well-defined metrics: $f_D$ and $f_S$, which correspond to the frequency to which a species is classified as a driver or superior node, respectively. 

In addition, we now focus exclusively on the results obtained when we use the asymmetry of the dependences to direct the networks. 
We do so, because thanks to the reviewers comments, we identyfied some novel problems with the application of structural controllability when we use the mutual dependences into direct the network. 
Specifically, the problems arise from an absolute dominance of cycles and difficulties to the use of the maximum maximum matching algorithm to find a minimum set of driver nodes $D$. 
We elaborate on these on the new version in Lines 201--212 and Supporting Information S6. 

Finally, we have made important modifications to the section in which we explain the theoretical underpinnings of structural controllability. 
We hope it is easier to follow both for experts and newcomers. 
We also have included a significant amount of detail and extra examples in the supplementary material to simplify the lives of those interested in applying the proposed approach or replicating our results. 

## Reviewer 1 (ELE-00738-2016)

In ms ELE-00738-2016, the authors seek to apply ideas from control theory (specifically, structural controllability) to bipartite ecological networks. The main idea of structural control theory, at least in the recent applied literature, is that some nodes are recipients of external, time-varying control signals that proceed to propagate through a network in such a way as to drive the state of every node in the network to a desired configuration in finite time. There tend to be many ways to do this, and nodes can further be characterized by the frequency with which they exist on key paths leading through the network.

These ideas have been used as additional measures to describe the topological characteristics of networks as they relate to their control. The novelty of the present ms is in extending these ideas in a rigorous way to mutualistic ecological networks, which to my knowledge has not yet been done (some existing work includes ecological networks, but usually in a somewhat cursory way).

This is a powerful premise and, at least in principle, a ms with such a focus could be a good candidate for publication in Ecology Letters. However, I have numerous concerns with the manuscript. The methodological assumptions of structural control are never discussed (i.e., what is the assumed form of the dynamic relationship between interacting nodes?), the extent to which this is or is not realistic in an ecological context is not discussed (it seems to me that there are important caveats), other details of the theory are left unexplained, a key term is used in a different context than in the control literature (which will needlessly confuse readers), and some of the statistical analysis seems questionable.

I expound on this overview in some detail below. I regret that I cannot be more enthusiastic about the manuscript in its current form and I wish the authors luck as they revise their manuscript.

- The authors begin by stating, "Complex systems are characterised by non-linear relationships...", however, there is an entire branch of work devoted to network control that explicitly assumes linearity on the level of specific interaction (see e.g. doi 10.1126/science.1242063 and doi 10.1038/nature10011, both of which the authors cite). It seems to me that the authors could simply remove this bit of text and restructure the sentence to make the same point -- that complex systems are often viewed as being "greater than the sum of its parts."

    *Accepted; changed.*

- The paragraph on lines 50-62 cites papers published no earlier than 2011. However, to support the following argument "Despite these advances, the link between the structure of complex networks and our ability to manage and conserve them is still ambiguous", the authors cite a paper that predates all of them (Tylianakis et al. 2010). The paper in question highlights practical challenges to conservation; many if not all of them remain today (which I suspect is the authors' argument). I suggest the authors revise the text to make the contribution of this reference clear.

    *We have now revised the text to better reflect the contribution of @Tylianakis2010. At the same time, we added a reference to a more recent paper by @Kaiser-Bunbury2015 that explicitly deals with opportunities, limitations and implications of applying network metrics in conservation science.*

- Lines 95-97: "The number of nodes necessary to fully control a complex network can be calculated by counting the number of unmatched nodes in the network's maximum matching (Liu et al. 97 2011)." This statement must be contextualized by the assumed nature of the dynamical relationships in this framework. It therefore seems to me that this statement should be preceded by a discussion of those details (indeed, the authors argue that this is necessary in the Introduction, on lines 48-49). Furthermore, the authors need to discuss the appropriateness of this framework to ecological systems. The input control signals that drive even relatively simple networks to specified states can be very sensitive to initial conditions and complicated (indeed, they usually aren't calculated at all). How can a control scheme be implemented even in principle if nodes represent species populations and a control signal calls for a fractional change in a node state variable over the course of minutes? 

    *Thanks for this comment and those from other reviewers which have helped us identify some shortcomings on the way we were introducing the control framework in the paper. In reposnse, we have largely rewritten the 'Theoretical framework' section. We start by offering a brief overview of control theory. In this overview, we emphasise our assumptions regarding the dynamical nature of the interactions. We then follow with a brief discussion that indicates how structural controllability is unable to provide information about the particulars of the control signal and the feasibility of its application. Without disregarding the usefulness of the proposed approach, we also mention at the end of the discussion how recently developed numerical methods [e.g. @Cornelius2013] might offer future avenues results in this regard (Lines 363--369)*
    
- Furthermore, how do the authors interpret the methods by which cycles are controlled in linear control theory (see e.g. doi 10.1126/science.1242063 and its supplementary material) in the context of ecological management? How frequent are cycles in the authors' ecological networks? I should emphasize that I am a fan of control theory and I think it is interesting to apply it as the authors do in this ms. However, the caveats that come along with the points I outline above need to be made clear for the reader. The authors might be interested in doi 10.1063/1.4931570 for a discussion of some relevant ideas.

    *Thanks for pointing this out. In fact, we explored the implementation of the approach of [@Ruths2014] at initial stages of the project. However, we earlier decided to exclude this approach from the final draft, mainly due to space limitations. Nevertheless, due to this comment and one of Referee 2 we have rediscovered its value and use it to support our decision to include the analysis of superior nodes, and not just driver nodes, in our manuscript. Though space constraints remain and we can only mention it briefly in the main text (Lines 328--330), we also dedicate a whole section in the Supporting Information (S2) to this subject. To summarise here, we found our networks weighted by asymmetry to be external dilation dominated, and hence have only a small number of cycles. Networks weighted by mutual dependences are dominated by cycles and hence challenging to address with our approach. In another section in the Supporting Information (S6), we discuss the implications of using these networks and our approach to circumvent them. Finally we are grateful for the reference to @Motter2015. We were unaware of this paper and it has been extremely useful to contextualise our work in the broader control-theory literature.* 
    
- Lines 101-103: "(ii) the sum of the weights of the matched links—known as matching weight—is the largest possible among all possible matchings of that size (West 2001)." The authors go on to cite Liu et al. 2011, but that report (and many others cited in the present ms) considers "structural controllability", which assumes binary edge weights (i.e., they exist or they do not). Is condition (ii) appropriate here? If so, why? The authors get at this later in the ms (lines 145-152, where it looks as if edges are indeed binarized), but for readers familiar with the structural control literature, there is room for confusion as they come to this point in the ms. This may be mitigated as the authors address my comment 3, but it seems appropriate for me to raise this point explicitly as well.


- When defining *n~d~* on line 119, it is more accurate to say that it is the "minimum number" of species needed to gain full control.

    *We have completely rewritten that section and the corresponding sentence (Lines 84--86) now reads "Conveniently the information necessary to determine the minimum number of driver nodes *D* in a network with linear dynamics is fully contained in the network structure..."*

- Lines 132-133: "...we therefore call driver species those that are identified as being a superior node in all possible matchings..."
I have several comments here. First, shouldn't this be "all possible maximum matchings"?

    *We are sorry for the imprecision. It should have been "all possible maximal-cardinality matchings". In any case, because of the reviewers' suggestion about the driver species concept, we have now removed this sentence altogether. We hope that the new text we have included in the "Relative importance" subsections, both in the "Theoretical framework" and "Empirical application" section, and in Supporting Information S7, helps clarify why our approach to identify species importance is not exclusively centred on maximum matchings.*

- Second, a node with no outgoing edges will clearly never be a superior node and will therefore not be a driver node. I assume that this never happens in the mutualistic networks under consideration, but this probably bears mentioning so as to help develop the reader's intuition for this assessment. In any event it would be useful for the reader to see a simple network (or several) to provide clear examples of driver nodes and non-driver nodes. For instance, how can a node with an outgoing edge not be a driver node?

    *Thanks to this suggestion and those of other reviewers, we have made important changes to Figure 1. In it, we include a better illustration of our methodology for a simple network while paying special effort to bring clarity to the different node categories of superior, driver, matched, and unmatched nodes. We hope the figure, in addition to our new introduction to the elements of a maximum matching, make the concept easier to understand.*

- Finally, the term "driver species" (or more generically, "driver node") has a specific meaning in the control literature (doi 10.1038/nature10011): what the authors here denote with n_d on line 118. To avoid confusion with those familiar with the control theory literature (and those readers who are inspired by this ms to delve into it), I suggest a change of terminology. Perhaps "key species"?

    *In hindsight, we agree that our choice of terminology was poor. We have eliminated the term "driver species", which had a different meaning to the usual concept of "control node", from the manuscript. Now, we stick to the terminology that is already used, and refrain for introducing a new term for species that are classified as superior nodes in all possible control strategies.*

- The approach described in lines 145-152 would be clearer if the authors included a figure demonstrating each step for a simple network.

    *Thanks for pointing this out. Exactly as suggested, we have included a figure that helps explain our method to compute all possible maximum cardinality matchings. Nevertheless, because of space limitations and because the methodology itself is not one of our main contributions, we have included the procedure and the figure in the Supporting Information (S1 and Figure S2).* 

- Lines 173-176: "To do so, we calculated the maximum matching of the corresponding pollination network, and estimated the minimum proportion of species that need directed interventions to fully control the species abundances in the community." Why is this an estimate? The number of species that need to be directly controlled can be determined unambiguously.

    *We again apologise for the poor choice of words. As the referee points out it, this is not an estimation but an exact calculation. The sentence (Lines 178--180) now reads "To do so, we calculated the networks' maximum matching and determined the minimum proportion of species *n~D~* that need external input signals to fully control the species abundances in the community".*

- It seems to me that the number of interactions would also be an interesting factor to consider in the statistical analysis (discussed beginning on line 213).

    *Thanks for the observation. We have now included the network connectance as an extra explanatory variable. We included connectance (link density) and not the number of links, because it allows comparisons across multiple networks of differing size. We found it to have a negative and moderate relationship with the density of driver nodes.*

- Lines 225-228: "Previous research indicates a direct link between a network's degree distribution and the number of nodes necessary to fully control it (Liu et al. 2011), but the strength and applicability of this relationship has not been tested for in weighted ecological networks." The authors go on to discuss null models that vary edge weights. However (as mentioned in comment 4), it seems to me that the edge weight is ultimately not a factor when determining the manageability of the network, at least once it has been mapped to unidirectional and unweighted edges. The methodology and rationale here needs to be clarified. For instance, is the effect of changing edge weight restricted to affecting interaction asymmetry and thereby the unidirectional projection of the interactions? If so, how does this differ from the null model that does this explicitly (described on lines 239-246)? Does edge weight play any other role in this analysis? (Its role is clear in the section beginning on line 247.)

    *In retrospect, we realise that our rationale to include a randomisation of the link weights was not clear enough. As the referee points out, a change to the weights would only be reflected in a potential change on the interaction asymmetry. We identifyed two problems with this approach: first the changes aren't easily tractable, and second there is not a standard way to randomise weights in quantiative networks and the particular choice of the algorithm might influence the results. We therefore decided to remove the null model that maintained the degree of species and randomised the weight of the links as the effect of the asymmetry is explicitly tackled by the second approach in which we maintain the structure but randomise the asymmetries.*

- It seems useful to mention the typical size of the networks at the beginning of the results, if not earlier. In addition, the fact that the mean value of m is 0.37 means that roughly two thirds of the species in these communities need to be directly controlled, at least according to this modeling framework. It seems to me that this merits explicit comment in the Discussion.

    *Thanks for the suggestion. In the methods where we describe the empirical application, we now state the minimum, maximum, and the mean number of species for both the networks from Bristol, UK and Cap de Creus, Spain. In addition, now we briefly discuss the proportion of driver nodes we found in the pollination networks in the fourth paragraph of the Discussion. We also do so in the context of highlighting the potential caveats of one of our metrics of species importance.*

- Indeed, in the Discussion the authors say for example, "Because of their effects on other species in the community, driver species might be natural candidates for management interventions." This may be true, but it seems to me that the role of the directly-controlled species (that populate n_d), which serve as the gateway for the control signals to the rest of the network, merits discussion here as well. How are the two related? Do the authors envision a scenario where a control signal is actually being sent in to the network? Or do they rather envision a scenario where no controls are being used (which is counter to the central idea of structural controllability), and are they instead identifying these drivers nodes simply to provide a proxy measure of the effect of node state perturbations on the rest of the network? The latter seems more plausible than the former, but in any case more detail is needed.

    *We agree completely with the Reviewer here. Given that driver nodes have received a considerable amount of attention in the control literature, we now realise that neglecting them might be confusing, especially for readers familiar with control theory. We have fully incorporated this suggestion and our paper is now much more comprehensive. To determine the potential importance of a species in the revised manuscript, we determine not only its properties as a superior node but also its properties as a driver node. We have dedicated a large proportion of the discussion to discuss the advantages and limitations of each of these, plus how they relate to each other and to realistic management applications. To do build this discussion, we harnessed results from additional modelling analysis in the main text, as well as the lessons learned from the application of the @Ruths2014 control-profiles approach.*

- Figure 3 should show the distributions of m as well as the adjusted value of m. I suggest also providing more detail about how the adjusted value is calculated (in the current version there is one technical sentence that non-experts will not be able to follow).

    *We have now included a subpanel in Figure 3 that depicts the distribution of _n~D~_ for our empirical networks. The adjusted values were merely partial residuals of the fitted statistical models. We therefore have changed the axis titles to reflect this fact and avoid confusion.*

- In Appendix S2 (referenced in the ms on lines 205-208), the authors state that the relative number of driver species, while different for the approaches there discussed, are not significantly different from one another. However, the statistical test used is a Spearman correlation coefficient, which does not measure the difference in e.g. population means but rather the extent to which their relationship is monotonic.

    *This was a mistake on our part. We were not interested in determining whether the __absolute__ value of n~D~ differs among approaches, but instead, we wanted to determine whether the __relative__ values showed agreement. That is, our primary concern was to test whether networks with a high n~D~ under the asymmetry weighting also had a high n~D~ under the bidirectional dependences weighting. We have changed the text in the Supporting Information (S6) to improve clarity.*

- Minor comments. Line  236: there is a missing period.

    *Thanks for pointing this out. We have added the period.*

## Referee 2 (ELE-00738-2016)

This manuscript proposes to apply the methods published in previous papers (e.g. Liu et al, Nature 2011) on the controllability of complex systems to invaded pollination networks. Note that controllability is rebranded “manageability” (unless it has a different meaning in this paper?). The manuscript also proposes to identify the nodes to manage or driver species. This is a fascinating area of research.

Performing a controllability study on ten pairs of uninvaded and invaded plant-pollinator networks, the main finding is that invaded networks require a higher number of nodes to control than their non-invaded counterpart and invasive plants were driver species in all studied communities.
The study is scientifically sound. However the manuscript is dense and difficult to read. In particular the section Theoretical framework and its subsection are confusing and should be merged with the Methods section. The discussion should be strengthen.

In its current form, it is unlikely that readers will be able to understand or replicate the research presented – which is a shame considering the authors went through a lot of trouble to apply a control theory study in an ecological context. An overall simplification of the language/sentences and jargon used will increase the readability of this manuscript. Ruths (2014, Science) and Liu (2011, Nature) are doing a better job at explaining maximum matching, driver nodes and the overall challenge of controllability.

- Consider being more specific in your abstract.

    *Given the tight 150 word limit imposed by the journal, we had some trouble highlighting the novelty of our approach while also maintaining important details about the empirical application. We hope the revised version of the abstract is improved in this regard.*

- L74 “we expand previous theory of the control of complex systems to an ecological context”. Do you mean apply? Please clarify your contribution without ambiguity.

    *The sentence (Lines 68--69) now reads "To bridge this gap, we outline an approach to apply theory on the control of complex systems in an ecological context and implement it using empirical data."*

- Section Manageability (L94). Please first define manageability before maximum matching. Also, the maximum matching paragraph is difficult to understand. Reword.

    *In response to this and other comments, we have rewritten most of the "Theoretical framework" section. We start with a brief introduction to structural controllability, follow with a definition of manageability and finalise with details and computational and methodological considerations regarding its calculation.*

- Section Relative importance (L121). It seems that the abstract refers to this section as being a novel way to identify communities’ driver species. However it is very unclear that this is a novel contribution. Please clarify in the text and provide details in supplementary information. It is also unclear from the Methods section.

     *Thanks for the observation. As above, we have also reworded large segments of this section to make what are and what are not novel contributions clearer. Specifically, we now explain how the approach builds on existing structural-controllability theory by incorporating the weight of the interactions. In addition, although the concept of driver and superior nodes are not novel in the control theory literature, most of the previous studies tend to focus on a __single__ matching. Here, we instead exploit the fact that a single network may have multiple control configurations and evaluate the role of species in each of them. We now dedicate a large proportion of the discussion to these new metrics and how (even if not independent) they are conceptually different to previous attempts to rank species by importance. We also include extra development in the Supporting Information S7. Moreover, now we include more details about the rationale behind our approach. By being more specific, we hope the reader to be able to identify the theoretical and computational novelties of our approach with respect to existing "ranking" methods.*

- Discussion. McDonaldMadden et al (2016) actually show that network metrics are not useful to prioritise the management of foodweb, i.e. to determine which species should be managed first (if required). Please edit current text and analyse differences with your work.

    *Thank you for this suggestion. We acknowledge that we did a poor job embodying our work in the previous literature. We now include a paragraph in the discussion to explore the similarities and differences of our work with previous indices based on structural metrics. We explain (Lines 349--351) how "our approach... is not based on a single structural metric but instead acknowledges the existence of multiple management strategies. By allowing for the fact that some strategies are better than others depending on the context, control theory implicitly highlights that management decisions should not be based on a single technique". We also concur that more flexible approaches like ours and the one implemented by @McDonald-Madden2016 "that take a network-wide approach might prove more useful to guide ecosystem management if we want to go beyond using network metrics to minimise topological species loss".*

- Discussion. Please provide some insight into how your method/analysis/results would differ for non- pollinator invaded networks.

    *We now brifly mention in the Discussion (Lines 356--358) how "although our pollination specific results might not be directly translatable to other ecological systems because of the degree constrains imposed by bipartite networks, the approach we propose is applicable wherever species abundances are influenced by their interactions...".*

- Discussion. Please discuss the caveats of your approach. I suggest moving some of the statistical analyses in sup info if word limit is an issue.

    *We agree that we did not previously discuss the assumptions and caveats of our approach with enough detail. As such, as we now try to better highlight the rationale behind our methods while being more explicit about the assumptions and limitations. Moreover we now provide a fairer assessment of the extent to which our approach might be useful for practical applications in the discussion. We note, however that the extended discussion (alongside with a better development of the theoretical framework), meant that we had to move some of the details about the statistical analysis to the Supporting Information (as suggested).*

- The maximum matching algorithm is computationally expensive as noted by the authors. In Ruths & Ruths (2014) the authors come with an interesting alternative to calculate the minimum number of independent controls (driver species) using only the number of source nodes, external dilation points and internal dilation points; and a heuristic using source and sink nodes. What is the profile of the pollinator networks studied? Would the Ruths & Ruths approach be an easier way of reaching the same conclusions? Would it bring complementary information?

    *Calculating __one__ maximum matching for ecological networks with a few hundred species is not a computationally expensive operation, and therefore we use directly the algorithm and not the approximation proposed by @Ruths2014. Our most expensive computation was to find __all__ the possible maximum cardinality matchings to calculate species-level metrics. Unfortunately, a network's control profile simply does not provide species-level information and hence we couldn't use it to our advantage. Nevertheless, as suggested here and by another reviewer, we have included a section in the Supporting Information (S2) where we explain that our networks are external dilation dominated. Consequently, the approach of @Ruths2014 has provided us with very useful insight on the selection of the direction of control and the utility of the concept of driver nodes for management applications (Lines 208--211 and 328--330).*

- A few typos in main text and sup info.

    *We have spellchecked and revised all the text and hope that this time no typos have escaped us.*

- Is there a compelling reason to change controllability to “manageability”? Walters did the same thing with “adaptive management” in lieu of “adaptive control”. 30 years later, no one remembers where “adaptive management” originally came from and it has become a keyword in ecology. As a result, ecologists have been cut from the theoretical advances in control theory and most often have no clue that these are the same thing.

    *Thank you for pointing this out. We still use the word within our manuscript because we found it is useful for to develop their intuition relative to ecological and conservation terminology. However, we do not use the word "manageability" as exchangable with "controllability" anymore and maintain the control-theory terminology, especially in the methods section. In addition, we have added additional references so that its easier for the readers to link back our approach to the control literature.*

## Referee 3 (ELE-00738-2016)

In this work Cagua et al apply tools rooted in control theory to ecological networks and discuss how this approach could be used for management of natural systems, with emphasis on the effects of invasive species. This is an exciting work. It presents to ecologists a novel way of studying the relationship between topology and dynamics that is less dependent (when compared to other methods) on particular choices about how dynamics are modeled. The authors illustrate the potential of this approach by exploring how invasive species change system dynamics and manageability. My only concern about this manuscript is that the authors need to be more careful and more explicit about some limitations of this approach and the generality of their results, specially considering the implications of their results for management.

- Only one type of interaction is being considered here when species are involved in multiple types of interactions. An assumption that is not explicit in the text is that all the factors controlling population densities are the interactions between plants and pollinators. The boundaries of a network, including the types of interactions that are considered or not, are often arbitrarily defined. However, this approach is highly dependent on the topology of the network and thus on how we define the network. I know this limitation applies to any study on system dynamics, but it becomes more serious when we argue that management decisions can be based on a single technique. I have two suggestions. First, the authors should discuss in detail these assumptions and their limitations.

    *We have now included comments about the general limitations of the structural-controllability approach in the "Theoretical framework" section. Furthermore, we are now explicit about the fact that species have multiple types of interactions and therefore our approach can only provide a partial picture when only one type of interaction is included (Lines 361--362). Finally, we are also explicit about the fact that we do not advocate for management decisions to be based solely on our approach (Lines 351--353).*

- Second, It would be helpful if the authors could test the robustness of their results to sampling. The results show that invasive species change manageability. This suggests that manageability may be sensitive to sampling. A sensitivity analysis where species are added and removed from the network under different wiring schemes would help us understand the behavior of the manageability index when networks are undersampled and would allow a more informed discussion on how the choices we make when delimiting the network affect estimates of controllability. Weak links should not have a strong effect on controllability and considering the networks were built using visitation frequency, most of the strong interactions were likely sampled. Still, it would be great to show that the method is robust and this would make it easier to justify that even in the absence of complete sampling this technique is in fact useful for management.

    *As suggested, we have conducted a sensitivity analysis in which we remove links from our empirical networks with a probability inversely proportional to their strength. Due to space constraints, we have included the analysis in the Supporting Information S5. Notably, we found that our results are consistent even in serious cases of undersampling.*

- Ln 25. I don't think that the statement that you "expand theory on the controllability of complex systems" is accurate. It is not clear to me how these results contribute to expand the general theory

    *Thank you. We apologise for the imprecision. The sentence (Lines 68--69) now reads "To bridge this gap, we outline an approach to apply theory on the control of complex systems in an ecological context and implement it using empirical data".*

- Ln 52, typo: presents

    *Thanks. It's been changed.*

- Ln 59. Please rewrite this sentence. it's not clear what "they" refers to here.

    *Thanks. We have rephrased the sentence (Lines 52--53) to improve clarity and it now reads "Therefore, control theory could also be harnessed to provide an indication of which species are most relevant from a structural and dynamic perspective".* 

- Ln 78. It is not clear why this is the direction of the hypothesis. Did you already have any indication that networks with invasive species should have lower manageability? Is there any theoretical explanation for this expectation?

    *We based the direction of the hypothesis in the general feeling of failure of several restoration ecology programmes. However, in retrospect, we realise that we presented insufficient academic evidence to substantiate the hypotheis. Although the results have changed after the discovery of a mistake on the analysis, we have not changed the original direction of the hypothesis. Nevertheless, we have reframed the sentence to explain it better: "... grounded on the difficulties usually involved with invasive species eradication and ecosystem restoration [@Woodford2016], we ask whether invaded networks have lower levels of manageability than their uninvaded counterparts; that is, whether they require a greater proportion of species to be managed to achieve the same level of control"*

- Ln 95-98. It is very hard to keep track of all those definitions - matching, matched nodes, matched links, matching size, matching weight, maximum matching. I found myself going back and forth several times between the framework, methods and results sections. A glossary would help a lot.

    *We have rewritten a large section of the methods and tried to be more clear when defining new terms by providing some examples and using a more logical sequence to go from one concept to the next. We have also included a short glossary with the most important definitions at the end of the manuscript.*

- Ln 99. Indicate how the matching is represented in the figure. e.g.,  "(dark grey links in Figure 1a)". Figure 1.Indicate the driver nodes in these networks

    *We have redesigned Figure 1 and now we indicate more clearly how the matching works and specify which are the superior, matched, and unmatched nodes. Because we also illustrate the methods to obtain the relative importance, it is now easier to highlight which are the key species in a simple network.*

- Ln 128. Be clear about the meaning of resources here. I understand you mean financial resources not  resources in the ecological sense.

    *We apologise for the imprecision as we meant financial resources. We have modified the sentence to improve clarity (Lines 128--131) and it now reads "Ecologically, potential differences between species are relevant because management and conservation resources are limited, and therefore ecological interventions should be focused on the set of species that might provide the largest impact".*

- Ln 236. Typo: missing period

    *Thanks. We corrected it.*

- Ln 293: Typo: reference

    *Thanks. We corrected it.*

- Ln 303-305. Please explain here which is the response variable that the ratio of plant to pollinator can explain.

    *We have attempted to eliminate ambiguity by rephrasing the sentence (Lines 266--268). It now reads "... of the various covariates we explored, the ratio of plants to pollinators showed the strongest relationship with n~D~".*

- Ln 326. "The strength of the dependency" has been defined as species strength by Bascompte et al. 2006. Why are you using a different term here?  When you say strength of the dependency it is not clear if you mean strength of dependencies of a given species on other species or the strength of the dependencies of all species on the species of interest. Moreover sometimes you use dependence and others dependency.

    *We apologise for the potential confusion. By "the strength of dependency" we meant species strength as defined by @Bascompte2006. We have modified the text in the Methods and the Results to avoid potential confusion. We also stick to dependence throughout the manuscript*

- Ln 336. Liu et al. 2011 found that driver nodes were often peripheral nodes in the network instead of network hubs. Here you find the opposite. How can you explain these differences?

    *In fact, our results agree with those of @Liu2011. However, this was likely confusing because our poor choice of terminology (we used driver species as a term to refer to species with a high probability of being superior nodes). Using our results, and insights obtained from @Ruths2014, we now explain that peripheral nodes tend to be driver because they are needed to achieve full control, but that network hubs are also often driver nodes, as they act as source nodes from which control signals can be transferred. Furthermore, our analysis at the species level is now more comprehensive, as it includes information on their role as both driver and superior nodes.*

- Ln 343 and Figure 4. Here and in the figure legend you say the level of manageability of empirical networks is lower, but in the figure you show an index that goes in the opposite direction, i.e.,  we see lower values for the randomization. It would be better to present these results in a more intuitive way.

    *Figure 4 represents the rank of the emprical network compared to that of the randomisations. We have now included explanatory arrows and modified the axis titles and the caption to facilitate the interpretation. Hopefully it's now much easier to understand.*

- Ln 362. Again the idea that supergeneralists tend to be driver species contrasts with Liu et al. results. This should be explored in more detail in the discussion.

    *The clarifications we provide in the response to the comment for Line 336 should help carify this comment as well. We hope that the discussion, which now clearly distinguishes between driver and superior nodes further explains the apparent contrasting results.*

- Ln 372. It is important to say that vulnerability is related change, but that it is had to predict in which direction the system will change

    *Thank you. We have implemented this suggestion and the text (Lines 341-343) now reads "Not only it is hard to predict the direction in which the system will change, but invaded communities also tend to be highly dependent on invaders and therefore acutely vulnerable to their eradication"*

- Figure 5 legend. Please include here the definition of dependency strength so the reader does not need to go back and forth.

    *Done.* 

## References
