---
title: "Keystoneness, centrality, and the structural controllability of ecological networks"
subtitle: "JEcol-2018-0545 - Detailed response to comments"
author: "Fernando Cagua, Kate L. Wootton, Daniel B. Stouffer"
classoption: a4paper
csl: journal-of-ecology.csl
documentclass: artikel1
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
    number_sections: false
header-includes:
  - \usepackage{setspace}
  - \usepackage{xr}
  - \usepackage{lineno}
  - \newcommand{\R}[1]{\label{#1}\linelabel{#1}}
  - \newcommand{\lr}[1]{page~\pageref{#1}, line~\lineref{#1}}
  - \externaldocument[M-]{manuscript}
  - \externaldocument[S-]{supp-info}
  - \usepackage[most]{tcolorbox}
  - \definecolor{block-gray}{gray}{0.9}
  - \newtcolorbox{myquote}{colback=block-gray,grow to right by=-10mm,grow to left by=-10mm, boxrule=0pt,boxsep=0pt,breakable}
---

\doublespacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE)
```

We are thankful to the assistant editor James Ross, the senior editor and David Gibson, and three anonymous reviewers for the insightful comments to improve the manuscript. 
In the following sections, you can find a detailed response to each comment raised during the previous round of review. 

# Associate Editor's comments:

> "I think this ms now makes much clearer the potential insights to be gained by applying control theory to interaction networks. In particular, the authors have done a nice job of explaining how their findings reinforce existing ideas in the literature on the stability of ecological networks while also acknowledging limitations. The reviewers identify a few remaining issues that should be straightforward to address. I also noticed a few issues"

Thank you for the positive feedback. We have addressed all of the specific issues raised and highlight these in red text in our resubmitted manuscript. 

> "*L9*: I think here and throughout much of the text, species should be possessive when followed by a noun ("species role" should be "species' role"). The possessive is currently used in some instances but is inconsistently applied throughout the ms."

*Accepted and changed*. We have checked through the manuscript and corrected this where relevant. Besides *specie's role*, we also changes instances of *species' contribution*, *species' degree*, *species' control capacity*, among others. 

> "*L25*: 'every invasive species in our dataset was part of it' Here it was unclear what 'it' refers to (the set of critical species), and the reference to a singular dataset when you have 20 networks in total was a bit confusing to me.

*Accepted and changed*. We have made this clearer as follows: "and included every invasive species in our dataset" (\lr{M-R2-our-dataset})

> "*L23-26*: in these lines, you refer to critical species, but I think the distinction between having high control capacity versus being critical needs to be defined (briefly) earlier (it is stated in *L18-19* that you will quantify both control capacity and identify critical species, but it is not explained how they are distinct)."

*Accepted and changed*. We now identify the distinction between high control capacity and being critical on \lr{M-R2-define-control-capacity}. The text now reads "It also allows us to quantify a species control capacity-its relative importance-and identify the set of species that, collectively, are critical in this context because they have largest possible control capacity."

> "*L27*: unclear what 'its' refers  to."

*Accepted and changed*. We now explicitly state "species' degree" in  \lr{M-R2-species-degree}

> "*L234, 235*: awkward to refer to species as 'they' and 'their'"

*Accepted and changed*. We have changed this to "it" and "its"

> "*L296*: 'More details in Supporting Information.' is a sentence fragment."

*Accepted and changed*. We have corrected this on \lr{M-R2-sentence-fragment}. The text now reads "See Supporting Information Section \@ref(S-visitation-as-proxy) for more details".

> "*L343*: I am not sure about citing Table 2 for the first time in the Discussion. Might it be more useful to cite this in the Introduction?""

We now introduce the glossary at the end of the introdyction on \lr{M-R2-ref-glossary}.

> "*L111, 114*: 'are comprised of' should be 'comprised'. *L339, 432*: 'at' should be 'in'. *L341*: 'allow' should be 'allowed'. *L355*: missing period."

*Accepted and changed*. Thank you for pointing out these mistakes, we corrected all of them.

# Reviewer comments #1

> "I'd like to commend the authors to this revised version of the manuscript on 'Keystoneness, centrality, and the structural controllability of ecological networks'. I thoroughly enjoyed the re-written manuscript, which is now considerably more accessible and clearly targets the community of network ecologists, while not ignoring the importance of the applied relevance of the findings. Overall, I don't have any major comments. I guess the language is in parts on the casual side, yet without compromising the preciseness or clarity of the text. I noticed a few typos or style errors that the authors may want to address. Congratulations on this thought-provoking methodological synthesis."

We are pleased that the reviewer enjoyed the re-written manuscript. We did too!. We also grateful for the typos and style errors identifyed, we have striven to correct them all. 

> "A few references require editing to journal style (e.g. remove initials for many citations)"

*Accepted and changed*. We have corrected all citations. One of them, however, (\lr{R2-citation-with-name}) still shows an author's first name initial, as it is necessary to distinguish two authors with the same last name.

> "*L388*: remove repeated 'other'. I suggest that the authors re-write this sentence to improve clarity."

*Accepted and changed*. We have removed the second 'other'. As suggested, we have rewritten the sentence to improve clarity (\lr{M-R2-structural-controllability}). It now reads as follows: "First, structural controllability emphasizes that the effect a species has on the abundance of other species is not independent of the effects of those other species in their community".

> "Reference list needs updating, e.g. Ne'eman et al. is not 2009 but 2010."

*Accepted and changed*. Thanks for pointing this error out. We've corrected the reference. 

> "*L314*: open bracket missing. *L358*: change 'instead' to 'Instead'. *L381*: remove second comma. *Fig. S6* header of plot b). correct spelling of 'critical'."

*Accepted and changed*. Thank you for pointing this out, made all these changes as indicated.

# Reviewer comments #2



> I think the concepts presented in this manuscript are a useful addition to the literature on management of ecological networks.  I agree with the authors that it is important that the discussion surrounding what constitutes a "keystone" species should go beyond centrality metrics.  



> I found the results and concepts to be generally well presented, particularly graphically, and the authors present a thorough sensitivity analysis to various assumptions.  The methods are mostly clear but there is no description of how the "likelihood of being a superior node " is calculated.  



> I would suggest including clarification on the limitations of using control capacity to summarise species' importance, and examples to help the reader build an intuition regarding the control capacity metric.  As pointed out, networks that give rise to a species having a high control capacity can be quite distinct to networks that give rise to a species having a high value of particular centrality metrics.  Providing an example in the Discussion of, for instance, those species that have a control capacity of 1 but a low degree would be very useful.  



> Jargon occasionally obfuscates the concepts being introduced and there are places where I thought the language used was vague (esp. if terms being used have particular meanings depending on the field you're coming from).  I would suggest clarifying, or rewording, the following :


> * "desired control trajectory " - does this mean "final state"?

We have attempted to clarify this sentence as follows: Finding out exactly how difficult it is to control a network depends strongly on the particularities of the desired control trajectory (i.e. path to the desired final state)  as well as the dynamical relationship between nodes. \lr{R2-desired-control-trajectory}

> * "dynamic persistence"  (p17,l364)

> * "dynamic stability " (p17, l370)

> * "ecological objective" (p9) - simply 'objective' ? 

We have changed this to simply 'objective', as suggested (\lr{R2-ecol-objective}).

> * "central in their community " (p18, l 405)

> * "inherently different " (p18, l 406). The sentence spanning lines 407-410 is quite confusing  - please clarify.  

We rephrased this line as follows: "We found that it is not that invasive plants have some different mechanism for influencing the community compared to their native counterparts" \lr{R2-inherrently-different}.

> * "marginally affected by the topology of their interactions"  (p19, l 430)

We have rephrased this line as: "By accounting for network dynamics (even if in a simple way), structural stability incorporates more ecological realism, especially in the extreme scenario in which the structure of interactions within the community only marginally affects the community's state. Both native species and invasive plants tended to attain a high control capacity if they were important to network persistence, were abundant, and depended little on other species." \lr{R2-marginally-affected}.

> * "dominate the state [of their community ]" (p19, l436 & l441)

>* "species' strength " (Discussion)


>Minor typos:
* Figure S11 caption: "likelyhood" -> likelihood 
* References : several references use the term "plantPollinator", or "..."
* Figure S1b is referred to (supp. p4 ) but doesn't exist in the figure.  
* Page 18 Line 388: "other other" 
* "driver node density" (supp p12) -> "size of the minimum driver node set"?  









-------------------------------------------------------

# Previous response:

> "I agree with the AE and reviewers that this is an interesting and potentially important manuscript. I support the AE's decision to reject but invite resubmission for all the reasons mentioned. I encourage resubmission if you feel that you can better bring out the conceptual importance of their work for plant ecologists. If you wish to strengthen the applied focus with specific conservation recommendations then you may wish to submit to Journal of Applied Ecology. Reviewer 1 offers suggestions for both approaches. I hope that you choose the former."

Thanks to the Senior Editor, David Gibson, for his comments and his willingness to allow resubmission. 
After lengthy consideration of the two recommended alternatives, we have chosen to focus on the conceptual importance of our work in line with the editor's stated preference. 
To do this effectively, we ultimately ended up rewriting both the manuscript and the supplementary materials almost completely. We think the extra effort was worth it as we feel the current version does a much better job at explaining the utility and insights generated by the proposed approach. 

#  Associate Editor comments

> "Both reviewers see potential value in the application of control theory to species interaction networks and found the work to be of interest. I agree that the method and its application to plant-pollinator networks are interesting, particularly the findings that contrast invaded vs uninvaded networks and use novel metrics to describe the influence of invasive species in networks. Both reviewers also note, however, that the current ms falls short of clearly and convincingly demonstrating the utility of control theory in making management decisions. They call for more in-depth exploration and illustration of what novel and important contributions this method would make to conservation. For these reasons, this work may be better-suited to a more applied journal (e.g., Journal of Applied Ecology), assuming the ms is revised in the recommended direction."

We thank the Associate Editor, Nicole Rafferty, for the constructive feedback and highlighting the strengths of the paper. 
As we noted above in our response to the Senior Editor, we opted to use our revisions to strengthen the conceptual component rather than emphasising its application in specific management and conservation scenarios. 
We opted to take this decision for two main reasons. 
First, the empirical data we use does not explicitly include any management or conservation scenarios. 
As a consequence and despite the potential of the approach, we currently lack *direct* evidence of the utility of the approach for management decisions.
Second, we concluded that highlighting the conceptual approach offered a greater opportunity to draw attention to the strongest/most interesting aspects of the paper. 
Namely, the contrasts between invaded and uninvaded communities and the role of invasive species, as one of the reviewers points out.

# Reviewer comments #1

> "The management of complex ecological networks is of vast importance for the conservation of the natural world. While the field of ecological networks is vast few have tackled this question in a practical way. This paper would make a significant contribution to a field that needs to change direction if it is to help inform conservation as often purported in studies from this field."

We are grateful to the reviewer for the positive feedback and encouraging words. 

> "The control theory approach is very interesting. I think however there needs to be more clarity in the paper. It is hard to read. A reworking of it including using descriptions of the variable throughout instead of variable names would improve this."

Previously, we used two sections to explain our approach: a section called "Theoretical framework" where we described the control methods, and another called "Methods" where we described their application to empirical data. 
At that moment, we thought this was the best approach; in hindsight, we realise that separating these two aspects made it hard to understand the core control concepts and their relationship with ecology. 
As mentioned by the reviewer, this problem was compounded by abundant jargon and mathematical notation. 
To improve clarity, we have now combined the two sections into a single "Methods" section in which we explain the theory alongside with the empirical application. 
We also spend more time working through intuitive explanations of the concepts of control theory and have moved the most technical details to the supplementary information. 
This latter move (shifting the technical details to the supplementary information) allowed us to use far less jargon and simplify the notation. 
We hope that the reviewer agrees that the new version is easier to follow.

> "Better context needs to be given for previous work to look at the management of networks in ecology. There are a few papers and knowing how this one differs from these (not just the ones that look at node importance for example) is important. Some of these papers are mentioned in the discussion but in the intro, it is important to know what they do and why this paper is novel."  

Thanks for this observation. 
In line with feedback from both editors, we have chosen to emphasise on the conceptual aspects of the work and reduced the core question of management applications to appear only in the discussion. 
Nevertheless, we have also rewritten the introduction and took care to be clear at explaining how this study relates to and differs from previous work. 
In particular, we set the stage for our work by briefly explaining how keystoneness metrics are mainly based on centrality metrics and explicitly outline where and how the proposed work differs. 

> "Finally I think it is important to provide context about what kind of decisions are being made and could be informed by this approach. Who is managing plant-pollinator networks and what choices would they actually be making. Some examples should be expanded on. And also how would the outputs of this work actual inform choices and guide prioritization"

As it was explained in the previous response, we chose not to emphasize the empirical application of structural controllability in this paper. 
However, we acknowledge that the approach has potential to be applied in management and have hence described some insights that structural controllability could offer to the conservation of ecological networks (\lr{M-management-implications}).

> "And finally I think mentioning the extreme uncertainty mostly seen in networks in the real world is key, how can approaches deal with this needs to be discussed. What do we need to think about in terms of key information to use this approach?"

In the previous version, we discussed this uncertainty but it was unfortunately buried in the Supporting Information. 
We have now added a subsection in the Methods describing how we evaluate the impact of the uncertainty induced (i) by using visitation as a proxy of species interdependence and (ii) by incomplete sampling of rare interactions (\lr{M-testing-assumptions-line}). 
We found that the structural controllability approach is rather robust to these two sources of uncertainty (\lr{M-testing-assumptions-results-line}). 
Further details can be found in the Supporting Information Section \@ref(S-visitation-as-proxy) and \@ref(S-undersampling). 
In addition, we also included a brief description of the key information needed to apply the method in the Discussion (\lr{M-data-requirements}).

# Reviewer comments #2

> "I read with great interest the manuscript by Cagua et al. on 'Quantifying the manageability of pollination networks in an invasion context'. The authors use control theory to develop an approach to assess how ecological networks – here pollination networks – can be managed, and test the approach on ten pairs of invaded and uninvaded plant-pollinator communities. Overall, the methodological approach appears to be sound (I’m not familiar with control theory, so I’ll have to leave in-depth assessment to an expert), the descriptions and rationale behind the assumptions used to develop the methods are logical and reasonable, and the illustration of the concept using published networks seems appropriate. Also, although the manuscript may require a few minor edits it is well and clearly written. I do, however, have some concerns about the applicability of the approach and the findings, which I’ll describe in more detail below."

We are thankful to the reviewer for indicating the aspects which they believe were strengths of our work. We maintain the methodological approach in the latest version and have used these comments to help determine which elements were essential to maintain in the current revision. 

> "When I first read the title and the abstract of the manuscript I was excited about the prospect of reading about a way forward using ecological networks to improve ecosystem conservation. Now, having read the manuscript twice, I’m not persuaded that the proposed approach really advances our ability to conserve or restore ecological communities as the authors claim, or whether the approach provides primarily another, rather complex, way of analysing networks and describing the role of species in networks. As it is, the authors fail to convince me that the developed approach really advances our ability to prioritise species for ecosystem conservation, nor does the manuscript offer novel insights into the role and importance of certain species in a network and for ecosystem functioning. I’ve little doubt that there are ecological and theoretical justifications for combining control and network theory, but the authors don’t yet show that their proposed methods are overly useful in applied conservation."

> "I can see two ways forward: the authors re-arrange and re-word the manuscript to focus on the ecological advances that such an approach would bring to explaining and predicting network structure; or the authors describe in more detail a few scenarios in which conservation practitioners and managers could apply the proposed method to ‘improve’ management strategies or measure the efficacy of interventions. The latter would require a stronger justification of the advantages of control-theory approach compared to the classic species-level network metrics."

We are very thankful for the insightful identification of the manuscript weaknesses and especially for clearly identifying possible pathways to fix them. 
Following this suggestion and those of the editors, we chose to focus on how structural controllability offers a new perspective to understand the role of species in their community in the context of species "keystoneness". 
Despite this decision, we still discuss previous metrics since we found that the paper was much clearer after we being more explicit about how the approach differs from classic centrality metrics to estimate species importance. 
Note that these differences are discussed in the current version more in the light of network structure than in the design of efficient management interventions. 

> "In short, I feel that the manuscript is currently a hybrid between ecological theory and applied conservation without being fully beneficial for either of the two disciplines. With a few changes to the manuscript, the interpretation and presentation of the results, and a re-write of the discussion with more tangible points and concrete examples from practical experience, the manuscript has the potential to be a solid contribution to the field of applied ecology."

As mentioned earlier in a response to the editor, we found that in order to address effectively all concerns, a rewrite of the whole paper was needed. 
Although we have not gone in the applied ecology direction, we hope the current version addresses the fundamental reviewers concerns to their satisfaction. 

> "One last minor remark, the authors have overlooked some key references in the field of restoration/conservation and ecological interactions/networks, which would strengthen the manuscript further, e.g. 

> * Harvey, E., Gounand, I., Ward, C.L. & Altermatt, F. (2017) Bridging ecology and conservation: from ecological networks to ecosystem function. Journal of Applied Ecology, 54, 371-379; 
> * Devoto, M., Bailey, S., Craze, P. & Memmott, J. (2012) Understanding and planning ecological restoration of plant-pollinator networks. Ecology Letters, 15, 319-32; 
> * Kaiser-Bunbury, C.N., Mougal, J., Whittington, A.E., Valentin, T., Gabriel, R., Olesen, J.M. & Blüthgen, N. (2017) Ecosystem restoration strengthens pollination network resilience and function. Nature, 542, 223-227;
> * Pires, M.M., Marquitti, F.M.D. & Guimarães Jr, P.R. (2017) The friendship paradox in species-rich ecological networks: Implications for conservation and monitoring. Biological Conservation, 209, 245-252.

Thank you for pointing us toward these references. We have found them to be particularly useful to highlight the differences between structural controllability and other approaches (\lr{M-extra-references-1} and \lr{M-extra-references-2}) and to discuss the potential impact of invasive plants (\lr{M-extra-references-3}). 
